# The cluster join token is generated by Terraform, not by k3s itself and not
# typed by a human — it never appears as a literal in any .tf/.hcl source, and
# it's written to SSM directly by Terraform (not pushed by an instance), so
# every node can simply read it at boot with no boot-ordering race: from
# Terraform's point of view the parameter is fully created before any node
# that depends on it starts booting.
resource "random_password" "node_token" {
  length  = 64
  special = false # keeps it trivially safe to embed in a shell command with no quoting surprises
}

resource "aws_ssm_parameter" "node_token" {
  name  = "${var.parameter_path_prefix}/node-token"
  type  = "SecureString"
  value = random_password.node_token.result
  tags  = var.tags
}

# Every node (primary master, joiner master, worker) only ever reads — no
# instance role needs ssm:PutParameter, since Terraform owns both the token
# and (in masters.tf) the primary master's endpoint.
resource "aws_iam_policy" "k3s_read" {
  name        = "${var.name}-k3s-read"
  description = "Read-only access to this cluster's SSM parameters under ${var.parameter_path_prefix}/*"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["ssm:GetParameter", "ssm:GetParameters"]
        Resource = "arn:aws:ssm:${var.region}:${data.aws_caller_identity.current.account_id}:parameter${var.parameter_path_prefix}/*"
      },
      {
        # Cloud-config is static (the ec2 module only supports a plain file()
        # read, no per-cluster templating) so each node discovers its own
        # cluster's parameter path prefix at boot by reading back its own
        # "k3s-parameter-path-prefix" tag. DescribeTags has no per-resource
        # ARN scoping in IAM, hence Resource "*" here — it's read-only and
        # reveals nothing beyond what's already visible in this account.
        Effect   = "Allow"
        Action   = ["ec2:DescribeTags"]
        Resource = "*"
      }
    ]
  })

  tags = var.tags
}

data "aws_caller_identity" "current" {}
